//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstDemoEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class film
    {
        public int id_film { get; set; }
        public string title_film { get; set; }
        public string length_film { get; set; }
        public Nullable<System.DateTime> released_date { get; set; }
        public Nullable<int> id_realisator { get; set; }
    }
}
