<FirstScreen>
    GridLayout:
        cols: 1
        padding: 10
        Image:
            id: img
            size_hint_y: 0.8
        TextInput:
            id: user_query
            size_hint_y: 0.1
        Button:
            size_hint_y: 0.1
            text: 'Search Image'
            on_press: root.preview_image()

<RootWidget>
    FirstScreen:
        id: first_screen
        name: 'first_screen'
